import {
  SystemSettings,
  Role,
  Permission,
  User,
  MembershipPackage,
  AdItem,
  ScraperSource,
  ScraperJobItem,
  DocumentCategory,
  DocumentItem,
  ContentItem,
  SocialAccount,
  SocialPost,
  DashboardWidget,
  NotificationItem,
  CustomPage,
  MenuItem,
  MediaFile,
  FilterDefinition,
  AIAgent,
  AIExecutionLog,
  ModerationItem,
  SEOSettings,
  AnalyticsSummary,
  AuditLogEntry,
  SecurityMetrics,
  APIKeyItem,
  WebhookEndpoint,
  QueueJob,
  WorkerPoolStatus,
} from "./types";

export const initialSystemSettings: SystemSettings = {
  general: {
    siteName: "2Evrak",
    logoUrl: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=120&auto=format&fit=crop&q=80",
    faviconUrl: "/favicon.ico",
    description: "1 Milyon Öğretmen İçin Dijital Evrak, Plan, Yazılı ve Zümre Yönetim Platformu",
    language: "tr",
    timezone: "Europe/Istanbul (UTC+3)",
    currency: "TRY (₺)",
    contactPhone: "+90 (312) 413 13 00",
    contactEmail: "destek@2evrak.meb.gov.tr",
    maintenanceMode: false,
  },
  seo: {
    siteTitle: "2Evrak | Türkiye'nin En Kapsamlı Öğretmen Doküman ve Plan Havuzu",
    description: "MEB müfredatına tam uyumlu zümre tutanakları, yıllık ders planları, ortak yazılı sınav soruları ve ders materyalleri.",
    keywords: ["öğretmen evrakları", "yıllık plan indir", "zümre tutanağı", "meb ortak sınav", "ders planı"],
    canonicalUrl: "https://2evrak.com",
    robotsTxt: "User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /api/\nSitemap: https://2evrak.com/sitemap.xml",
    sitemapEnabled: true,
    defaultSchemaType: "EducationalOrganization",
    ogImageUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80",
  },
  performance: {
    cacheEngine: "redis",
    cacheEnabled: true,
    cdnUrl: "https://cdn.2evrak.com/assets",
    imageWebpAutoConvert: true,
    lazyLoading: true,
    apiRateLimitPerMin: 120,
  },
  security: {
    sessionTimeoutMinutes: 120,
    passwordMinLength: 8,
    requireSpecialChar: true,
    twoFactorAuthPolicy: "mandatory_for_staff",
    rateLimitEnabled: true,
    ipBlacklist: ["194.26.29.112", "45.154.255.89"],
    ipWhitelist: ["88.255.10.15"],
    allowedMimeTypes: [
      "application/pdf",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "image/jpeg",
      "image/png",
    ],
    maxUploadSizeMb: 50,
    auditLogRetentionDays: 365,
  },
};

export const initialPermissions: Permission[] = [
  { id: "perm_view", key: "view", name: "Görüntüleme", category: "Doküman", description: "Tüm evrakları ve içerikleri görüntüleme" },
  { id: "perm_create", key: "create", name: "Oluşturma", category: "Doküman", description: "Yeni doküman, sayfa ve zümre taslağı yükleme" },
  { id: "perm_edit", key: "edit", name: "Düzenleme", category: "Doküman", description: "Mevcut kayıtları güncelleme" },
  { id: "perm_delete", key: "delete", name: "Silme (Soft Delete)", category: "Doküman", description: "Kayıtları çöp kutusuna taşıma ve silme" },
  { id: "perm_publish", key: "publish", name: "Doğrudan Yayınlama", category: "İçerik", description: "Moderasyon beklemeden yayına alma yetkisi" },
  { id: "perm_moderate", key: "moderate", name: "Moderasyon Yönetimi", category: "Sistem", description: "Kuyruktaki kayıtları onaylama, revizyon isteme ve reddetme" },
  { id: "perm_import", key: "import", name: "Toplu İçe Aktarma", category: "Doküman", description: "Scraper veya zip ile toplu doküman alma" },
  { id: "perm_export", key: "export", name: "Dışa Aktarma", category: "Sistem", description: "Kullanıcı, log ve analitik verilerini CSV/JSON olarak indirme" },
  { id: "perm_manage", key: "manage_system", name: "Tam Sistem Yönetimi", category: "Sistem", description: "Sistem ayarları, roller, API ve güvenlik yönetimi" },
];

export const initialRoles: Role[] = [
  {
    id: "role_super_admin",
    name: "Süper Yönetici",
    slug: "super_admin",
    order: 1,
    permissions: ["view", "create", "edit", "delete", "publish", "moderate", "import", "export", "manage_system"],
    isSystemRole: true,
    color: "bg-red-500/10 text-red-400 border-red-500/20",
  },
  {
    id: "role_editor_in_chief",
    name: "Baş Editör",
    slug: "editor_in_chief",
    order: 2,
    permissions: ["view", "create", "edit", "publish", "moderate", "import", "export"],
    isSystemRole: false,
    color: "bg-purple-500/10 text-purple-400 border-purple-500/20",
  },
  {
    id: "role_moderator",
    name: "Doküman Moderatörü",
    slug: "moderator",
    order: 3,
    permissions: ["view", "edit", "moderate"],
    isSystemRole: false,
    color: "bg-amber-500/10 text-amber-400 border-amber-500/20",
  },
  {
    id: "role_branch_lead",
    name: "Zümre Başkanı",
    slug: "branch_lead",
    order: 4,
    permissions: ["view", "create", "edit"],
    isSystemRole: false,
    color: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  },
  {
    id: "role_teacher",
    name: "Öğretmen (Standart)",
    slug: "teacher",
    order: 5,
    permissions: ["view", "create"],
    isSystemRole: false,
    color: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
  },
];

export const initialUsers: User[] = [
  {
    id: "usr_1",
    fullName: "Prof. Dr. Ahmet Yılmaz",
    email: "ahmet.yilmaz@2evrak.com",
    roleId: "role_super_admin",
    packageId: "pkg_vip",
    status: "active",
    branch: "Bilişim Teknolojileri",
    schoolType: "BİLSEM",
    city: "Ankara",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    createdAt: "2024-01-10",
    lastLoginAt: "2026-09-12 09:42",
    twoFactorEnabled: true,
    documentsDownloaded: 1420,
    aiCreditsUsed: 380,
  },
  {
    id: "usr_2",
    fullName: "Zeynep Kaya",
    email: "zeynep.kaya@meb.k12.tr",
    roleId: "role_editor_in_chief",
    packageId: "pkg_pro",
    status: "active",
    branch: "Türk Dili ve Edebiyatı",
    schoolType: "Fen Lisesi",
    city: "İstanbul",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    createdAt: "2024-03-15",
    lastLoginAt: "2026-09-12 08:15",
    twoFactorEnabled: true,
    documentsDownloaded: 890,
    aiCreditsUsed: 620,
  },
  {
    id: "usr_3",
    fullName: "Mustafa Demir",
    email: "mustafa.demir@ogretmen.gov.tr",
    roleId: "role_moderator",
    packageId: "pkg_pro",
    status: "active",
    branch: "Matematik",
    schoolType: "Devlet Ortaokulu",
    city: "İzmir",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    createdAt: "2024-04-02",
    lastLoginAt: "2026-09-11 18:30",
    twoFactorEnabled: false,
    documentsDownloaded: 430,
    aiCreditsUsed: 140,
  },
  {
    id: "usr_4",
    fullName: "Elif Şahin",
    email: "elif.sahin@gmail.com",
    roleId: "role_teacher",
    packageId: "pkg_free",
    status: "active",
    branch: "Sınıf Öğretmenliği",
    schoolType: "Devlet İlkokulu",
    city: "Bursa",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    createdAt: "2024-08-20",
    lastLoginAt: "2026-09-12 10:01",
    twoFactorEnabled: false,
    documentsDownloaded: 74,
    aiCreditsUsed: 25,
  },
  {
    id: "usr_5",
    fullName: "Hasan Çelik",
    email: "hasan.celik@hotmail.com",
    roleId: "role_teacher",
    packageId: "pkg_free",
    status: "suspended",
    branch: "Fizik",
    schoolType: "Anadolu Lisesi",
    city: "Antalya",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    createdAt: "2024-06-11",
    lastLoginAt: "2026-08-14 11:20",
    twoFactorEnabled: false,
    documentsDownloaded: 12,
    aiCreditsUsed: 50,
  },
];

export const initialMembershipPackages: MembershipPackage[] = [
  {
    id: "pkg_free",
    name: "Temel Öğretmen (Ücretsiz)",
    badge: "ÜCRETSİZ",
    priceMonthly: 0,
    priceYearly: 0,
    isActive: true,
    order: 1,
    limits: {
      documentDownloadsPerDay: 10,
      aiCreditsPerMonth: 50,
      aiQuestionGenerationMonthly: 15,
      maxDocumentCreationMonthly: 10,
      storageMb: 250,
      canShareSocial: false,
      hasSpecialContentAccess: false,
      canExportPdfWord: true,
    },
    description: "Yeni başlayan ve temel MEB evraklarını indirmek isteyen öğretmenler için.",
  },
  {
    id: "pkg_pro",
    name: "Pro Öğretmen Paketi",
    badge: "EN POPÜLER",
    priceMonthly: 99,
    priceYearly: 890,
    isActive: true,
    order: 2,
    limits: {
      documentDownloadsPerDay: 100,
      aiCreditsPerMonth: 500,
      aiQuestionGenerationMonthly: 150,
      maxDocumentCreationMonthly: 100,
      storageMb: 2048,
      canShareSocial: true,
      hasSpecialContentAccess: true,
      canExportPdfWord: true,
    },
    description: "Yoğun evrak, soru hazırlama ve zümre planlaması yapan aktif branş öğretmenleri için.",
  },
  {
    id: "pkg_vip",
    name: "Zümre & Kurumsal VIP",
    badge: "SINIRSIZ",
    priceMonthly: 249,
    priceYearly: 2190,
    isActive: true,
    order: 3,
    limits: {
      documentDownloadsPerDay: 0, // 0 = sınırsız
      aiCreditsPerMonth: 3000,
      aiQuestionGenerationMonthly: 1000,
      maxDocumentCreationMonthly: 500,
      storageMb: 20480,
      canShareSocial: true,
      hasSpecialContentAccess: true,
      canExportPdfWord: true,
    },
    description: "Okul idarecileri, zümre başkanları ve sınırsız AI gücü arayan eğitimciler için.",
  },
];

export const initialAds: AdItem[] = [
  {
    id: "ad_1",
    name: "Eğitim Teknolojileri Zirvesi 2026",
    area: "header",
    type: "image",
    contentUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=900&auto=format&fit=crop&q=80",
    redirectUrl: "https://egitimzirvesi2026.com",
    isActive: true,
    startDate: "2026-09-01",
    endDate: "2026-10-30",
    priority: 9,
    targetPages: ["all"],
    targetCategories: ["all"],
    targetDevices: ["desktop", "tablet"],
    targetUserTypes: ["all"],
    impressionCap: 3,
    stats: {
      impressions: 142850,
      clicks: 4890,
      revenue: 12450,
    },
  },
  {
    id: "ad_2",
    name: "Öğretmenler İçin Dizüstü Bilgisayar Kampanyası",
    area: "sidebar",
    type: "native",
    htmlSnippet: "<div class='p-3 bg-indigo-900/30 rounded border border-indigo-700/50'><strong>Öğretmen İndirimi:</strong> %20 Eğitim İndirimi ile yeni nesil laptoplar!</div>",
    redirectUrl: "https://kampanya.orneketik.com",
    isActive: true,
    startDate: "2026-09-05",
    endDate: "2026-09-25",
    priority: 8,
    targetPages: ["document_detail", "category_view"],
    targetCategories: ["cat_temel", "cat_orta"],
    targetDevices: ["desktop", "mobile"],
    targetUserTypes: ["free_user", "guest"],
    impressionCap: 5,
    stats: {
      impressions: 98400,
      clicks: 3120,
      revenue: 8900,
    },
  },
  {
    id: "ad_3",
    name: "Akıllı Tahta Eğitim Yazılımı Tanıtımı",
    area: "content_inline",
    type: "html",
    htmlSnippet: "<div class='p-4 bg-emerald-950/40 border border-emerald-500/30 rounded-lg text-sm text-emerald-200'>🎓 MEB Akıllı Tahtalarına %100 uyumlu etkileşimli soru bankası yazılımını ücretsiz deneyin.</div>",
    redirectUrl: "https://akillitahta.orneketik.com",
    isActive: true,
    startDate: "2026-09-10",
    endDate: "2026-12-31",
    priority: 7,
    targetPages: ["document_detail"],
    targetCategories: ["all"],
    targetDevices: ["desktop", "mobile", "tablet"],
    targetUserTypes: ["all"],
    impressionCap: 2,
    stats: {
      impressions: 43200,
      clicks: 1840,
      revenue: 4600,
    },
  },
];

export const initialScraperSources: ScraperSource[] = [
  {
    id: "src_meb_duyurular",
    name: "MEB Resmi Duyurular ve Tebliğler",
    targetUrl: "https://www.meb.gov.tr/duyurular",
    isActive: true,
    scheduleCron: "0 */2 * * *", // Her 2 saatte bir
    lastRunAt: "2026-09-12 08:00",
    status: "idle",
    selectors: {
      container: ".duyuru-listesi .duyuru-item",
      title: "h3.baslik",
      content: ".detay-metin",
      fileUrl: "a.ek-dosya-link[href$='.pdf']",
      image: "img.kapak",
      date: ".tarih-etiketi",
    },
    autoCategoryMapping: [
      { ruleKeyword: "ortak sınav", targetCategoryId: "cat_yazili" },
      { ruleKeyword: "müfredat", targetCategoryId: "cat_planlar" },
      { ruleKeyword: "zümre", targetCategoryId: "cat_zumre" },
    ],
    autoTagMapping: ["meb duyuru", "resmi yazı", "mevzuat"],
    lastItemCount: 14,
  },
  {
    id: "src_eba_materyaller",
    name: "EBA Eğitim Bilişim Ağı Açık Kaynak Havuzu",
    targetUrl: "https://eba.gov.tr/dersler/calisma-kagitlari",
    isActive: true,
    scheduleCron: "0 4 * * *", // Her gece saat 04:00
    lastRunAt: "2026-09-12 04:00",
    status: "idle",
    selectors: {
      container: ".materyal-karti",
      title: ".kategori-adi",
      content: ".aciklama-text",
      fileUrl: "a[href*='indir']",
      image: ".thumbnail img",
      date: ".eklenme-tarihi",
    },
    autoCategoryMapping: [
      { ruleKeyword: "ilkokul", targetCategoryId: "cat_ilkokul" },
      { ruleKeyword: "ortaokul", targetCategoryId: "cat_ortaokul" },
      { ruleKeyword: "lise", targetCategoryId: "cat_lise" },
    ],
    autoTagMapping: ["eba", "etkinlik", "çalışma kağıdı"],
    lastItemCount: 42,
  },
  {
    id: "src_osym_sorular",
    name: "ÖSYM Çıkmış Sınavlar ve Kılavuzlar",
    targetUrl: "https://www.osym.gov.tr/duyuru-arsiv",
    isActive: false,
    scheduleCron: "0 0 * * 1", // Haftada 1 pazartesi
    lastRunAt: "2026-09-08 00:00",
    status: "paused",
    selectors: {
      container: ".arsiv-tablo tr",
      title: "td.duyuru-adi a",
      content: "td.aciklama",
      fileUrl: "td a[href*='pdf']",
      image: "",
      date: "td.tarih",
    },
    autoCategoryMapping: [
      { ruleKeyword: "yks", targetCategoryId: "cat_lise" },
      { ruleKeyword: "lgs", targetCategoryId: "cat_ortaokul" },
    ],
    autoTagMapping: ["çıkmış sorular", "ösym", "sınav arşivi"],
    lastItemCount: 8,
  },
];

export const initialScraperJobs: ScraperJobItem[] = [
  {
    id: "job_1",
    sourceId: "src_meb_duyurular",
    sourceName: "MEB Resmi Duyurular",
    rawTitle: "2025-2026 Eğitim Öğretim Yılı 1. Dönem Ortak Sınav Kılavuzu ve Konu Dağılımları",
    rawUrl: "https://www.meb.gov.tr/haberler/ortak-sinav-2025/129481",
    foundFiles: ["ortak_sinav_2025_kilavuz.pdf", "konu_dagilim_tablosu.xlsx"],
    scrapedAt: "2026-09-12 08:05",
    similarityScore: 0.02,
    isDuplicate: false,
    status: "moderation_queue",
    aiSummary: "MEB tarafından yayımlanan 6., 7., 9. ve 10. sınıflar için 1. dönem 1. yazılı ortak sınav esasları ve açık uçlu soru dağılımları.",
    suggestedCategoryId: "cat_yazili",
  },
  {
    id: "job_2",
    sourceId: "src_eba_materyaller",
    sourceName: "EBA Portali",
    rawTitle: "5. Sınıf Fen Bilimleri Güneş Sistemi Etkileşimli Çalışma Kağıdı",
    rawUrl: "https://eba.gov.tr/icerik/fen-5-gunes-sistemi",
    foundFiles: ["gunes_sistemi_calisma_karti.pdf"],
    scrapedAt: "2026-09-12 04:12",
    similarityScore: 0.88,
    isDuplicate: true,
    status: "discarded",
    aiSummary: "Daha önce sistemde mevcut olan içerikle %88 benzerlik tespit edildi.",
    suggestedCategoryId: "cat_ortaokul",
  },
];

// SINIRSIZ HİYERARŞİK KATEGORİ YAPISI (N-Seviye Derinlik)
export const initialDocumentCategories: DocumentCategory[] = [
  {
    id: "cat_temel",
    parentId: null,
    name: "Temel Eğitim (Okul Öncesi & İlkokul)",
    slug: "temel-egitim",
    description: "Okul öncesi ve 1, 2, 3, 4. sınıf evrak ve materyalleri",
    order: 1,
    isActive: true,
    itemCount: 4200,
  },
  {
    id: "cat_ilkokul",
    parentId: "cat_temel",
    name: "İlkokul (1-4. Sınıf)",
    slug: "ilkokul",
    description: "İlkokul tüm dersler ve branş evrakları",
    order: 1,
    isActive: true,
    itemCount: 3100,
  },
  {
    id: "cat_ilkokul_4",
    parentId: "cat_ilkokul",
    name: "4. Sınıf",
    slug: "4-sinif",
    description: "4. Sınıf tüm ders planları ve sınav evrakları",
    order: 4,
    isActive: true,
    itemCount: 1250,
  },
  {
    id: "cat_ilkokul_4_mat",
    parentId: "cat_ilkokul_4",
    name: "4. Sınıf Matematik",
    slug: "4-sinif-matematik",
    description: "4. sınıf matematik kazanımları ve çalışma fasikülleri",
    order: 1,
    isActive: true,
    itemCount: 540,
  },
  {
    id: "cat_ilkokul_4_mat_kesirler",
    parentId: "cat_ilkokul_4_mat",
    name: "Kesirler ve Kesir Problemleri",
    slug: "kesirler-ve-kesir-problemleri",
    description: "Sınırsız hiyerarşi örneği: 5. alt seviye kategori",
    order: 1,
    isActive: true,
    itemCount: 180,
  },
  {
    id: "cat_ortaokul",
    parentId: null,
    name: "Ortaokul (5-8. Sınıf)",
    slug: "ortaokul",
    description: "5, 6, 7 ve 8. sınıf LGS hazırlık ve ders planları",
    order: 2,
    isActive: true,
    itemCount: 5800,
  },
  {
    id: "cat_ortaokul_8",
    parentId: "cat_ortaokul",
    name: "8. Sınıf (LGS)",
    slug: "8-sinif-lgs",
    description: "LGS deneme sınavları, soru dağılım tabloları",
    order: 4,
    isActive: true,
    itemCount: 2400,
  },
  {
    id: "cat_lise",
    parentId: null,
    name: "Ortaöğretim (Lise 9-12. Sınıf)",
    slug: "ortaogretim-lise",
    description: "Anadolu, Fen, Sosyal Bilimler ve İmam Hatip Lisesi evrakları",
    order: 3,
    isActive: true,
    itemCount: 6900,
  },
  {
    id: "cat_zumre",
    parentId: null,
    name: "Zümre ve Kurul Tutanakları",
    slug: "zumre-ve-kurul-tutanaklari",
    description: "Sene başı, dönem sonu, ŞÖK ve veli toplantısı zümreleri",
    order: 4,
    isActive: true,
    itemCount: 8500,
  },
  {
    id: "cat_yazili",
    parentId: null,
    name: "Yazılı Sınavlar ve MEB Ortak Sınavlar",
    slug: "yazili-sinavlar-ortak-sinavlar",
    description: "Senaryo 1 ve Senaryo 2 uyumlu açık uçlu sınav örnekleri",
    order: 5,
    isActive: true,
    itemCount: 9200,
  },
  {
    id: "cat_planlar",
    parentId: null,
    name: "Yıllık Planlar (2025-2026)",
    slug: "yillik-planlar",
    description: "MEB güncel haftalık kazanım ve çerçeve yıllık planları",
    order: 6,
    isActive: true,
    itemCount: 7100,
  },
  {
    id: "cat_rehberlik",
    parentId: null,
    name: "Rehberlik & Özel Eğitim (BEP)",
    slug: "rehberlik-ve-bep",
    description: "Bireyselleştirilmiş Eğitim Planları (BEP) ve rehberlik evrakları",
    order: 7,
    isActive: true,
    itemCount: 3400,
  },
];

export const initialDocuments: DocumentItem[] = [
  {
    id: "doc_1",
    title: "2025-2026 Sene Başı Matematik Zümre Öğretmenler Kurulu Toplantı Tutanağı",
    description: "MEB ortaokul matematik zümresi için yeni maarif modeline uygun eksiksiz tutanak şablonu, gündem maddeleri ve imza sirküsü.",
    categoryId: "cat_zumre",
    subCategoryIds: ["cat_ortaokul"],
    schoolType: "Devlet Ortaokulu",
    gradeLevel: "Ortaokul",
    classNumber: "5-8. Sınıf",
    lesson: "Matematik",
    branch: "Matematik",
    subject: "Sene Başı Zümre Kararları",
    term: "Sene Başı",
    docType: "Zümre Tutanağı",
    year: "2025-2026",
    fileUrl: "/assets/docs/matematik_sene_basi_zumre_2025.docx",
    fileName: "matematik_sene_basi_zumre_2025.docx",
    fileType: "docx",
    fileSizeBytes: 245000,
    tags: ["zümre", "matematik", "sene başı", "meb", "2025-2026"],
    source: "Öğretmen Yüklemesi",
    authorId: "usr_3",
    authorName: "Mustafa Demir",
    status: "published",
    isSoftDeleted: false,
    downloadCount: 4210,
    viewCount: 11900,
    rating: 4.9,
    seo: {
      metaTitle: "2025-2026 Sene Başı Matematik Zümre Tutanağı İndir | 2Evrak",
      metaDescription: "Yeni MEB müfredatına tam uyumlu sene başı matematik zümre tutanağını docx formatında ücretsiz indirin.",
      keywords: ["matematik zümresi", "sene başı zümre", "2025 zümre tutanağı"],
    },
    createdAt: "2025-09-02 10:15",
    updatedAt: "2025-09-05 14:20",
  },
  {
    id: "doc_2",
    title: "7. Sınıf Türkçe 1. Dönem 1. Ortak Yazılı Sınavı (Senaryo 1 Açık Uçlu)",
    description: "MEB Ölçme ve Değerlendirme Genel Müdürlüğü konu-soru dağılım tablosuna %100 uygun cevap anahtarlı ve rubrikli yazılı sınavı.",
    categoryId: "cat_yazili",
    subCategoryIds: ["cat_ortaokul"],
    schoolType: "Devlet Ortaokulu",
    gradeLevel: "Ortaokul",
    classNumber: "7. Sınıf",
    lesson: "Türkçe",
    branch: "Türkçe",
    subject: "Fiillerde Anlam ve Paragrafta Anlam",
    term: "1. Dönem",
    docType: "Yazılı Sınavı",
    year: "2025-2026",
    fileUrl: "/assets/docs/7_sinif_turkce_1_donem_1_yazili.pdf",
    fileName: "7_sinif_turkce_1_donem_1_yazili.pdf",
    fileType: "pdf",
    fileSizeBytes: 412000,
    tags: ["türkçe yazılı", "7. sınıf", "ortak sınav", "açık uçlu", "senaryo 1"],
    source: "MEB Portali",
    authorId: "usr_2",
    authorName: "Zeynep Kaya",
    status: "published",
    isSoftDeleted: false,
    downloadCount: 7850,
    viewCount: 24300,
    rating: 4.95,
    seo: {
      metaTitle: "7. Sınıf Türkçe 1. Dönem 1. Yazılı Açık Uçlu Sınav Soruları | 2Evrak",
      metaDescription: "MEB ortak sınav senaryo 1 formatında 7. sınıf Türkçe 1. yazılı sınavı ve cevap anahtarı PDF indir.",
      keywords: ["7 sınıf türkçe yazılısı", "türkçe ortak sınav", "açık uçlu sorular"],
    },
    createdAt: "2025-10-14 09:30",
    updatedAt: "2025-10-15 11:00",
  },
  {
    id: "doc_3",
    title: "9. Sınıf Bilişim Teknolojileri ve Yazılım Yıllık Çerçeve Planı",
    description: "36 haftalık güncel MEB takvimine göre hazırlanmış, algoritmalar ve Python programlama modüllerini içeren yıllık ders planı.",
    categoryId: "cat_planlar",
    subCategoryIds: ["cat_lise"],
    schoolType: "Anadolu Lisesi",
    gradeLevel: "Lise",
    classNumber: "9. Sınıf",
    lesson: "Bilişim Teknolojileri",
    branch: "Bilişim Teknolojileri",
    subject: "Yıllık Plan",
    term: "Tüm Yıl",
    docType: "Yıllık Plan",
    year: "2025-2026",
    fileUrl: "/assets/docs/9_sinif_bilisim_yillik_plan_2025.docx",
    fileName: "9_sinif_bilisim_yillik_plan_2025.docx",
    fileType: "docx",
    fileSizeBytes: 310000,
    tags: ["bilişim", "yıllık plan", "9. sınıf", "python", "kodlama"],
    source: "Öğretmen Yüklemesi",
    authorId: "usr_1",
    authorName: "Prof. Dr. Ahmet Yılmaz",
    status: "published",
    isSoftDeleted: false,
    downloadCount: 3190,
    viewCount: 9400,
    rating: 4.8,
    seo: {
      metaTitle: "9. Sınıf Bilişim Teknolojileri Yıllık Planı 2025-2026 | 2Evrak",
      metaDescription: "Lise 9. sınıf bilişim teknolojileri ve yazılım yıllık ders planını docx formatında indir.",
      keywords: ["bilişim yıllık plan", "9 sınıf bilişim", "lise yıllık planları"],
    },
    createdAt: "2025-08-25 15:00",
    updatedAt: "2025-08-28 17:15",
  },
  {
    id: "doc_4",
    title: "Kişisel Gelişim ve Satranç Kulübü Yıllık Çalışma Dosyası ve Karar Tutanağı",
    description: "Sosyal etkinlikler yönetmeliğine uygun kulüp tüzüğü, öğrenci listesi, yıllık çalışma takvimi ve sene başı toplantı tutanağı paketi.",
    categoryId: "cat_zumre",
    subCategoryIds: ["cat_ortaokul", "cat_lise"],
    schoolType: "Devlet Okulu",
    gradeLevel: "Tüm Kademeler",
    classNumber: "Tüm Sınıflar",
    lesson: "Kulüp Etkinlikleri",
    branch: "Rehberlik / Sosyal Etkinlik",
    subject: "Kulüp Dosyası",
    term: "Sene Başı",
    docType: "Kulüp Evrakı",
    year: "2025-2026",
    fileUrl: "/assets/docs/satranc_kulubu_dosyasi_2025.zip",
    fileName: "satranc_kulubu_dosyasi_2025.zip",
    fileType: "zip",
    fileSizeBytes: 1250000,
    tags: ["kulüp dosyası", "satranç kulübü", "sosyal etkinlik", "toplantı tutanağı"],
    source: "Öğretmen Yüklemesi",
    authorId: "usr_4",
    authorName: "Elif Şahin",
    status: "pending_review",
    isSoftDeleted: false,
    downloadCount: 140,
    viewCount: 650,
    rating: 4.6,
    seo: {
      metaTitle: "Satranç Kulübü Yıllık Çalışma Dosyası İndir | 2Evrak",
      metaDescription: "MEB kulüp evrakları, satranç kulübü yıllık plan ve tutanak şablonu.",
      keywords: ["satranç kulübü", "kulüp dosyası", "kulüp planı"],
    },
    createdAt: "2026-09-11 14:20",
    updatedAt: "2026-09-11 14:20",
  },
  {
    id: "doc_5",
    title: "Bireyselleştirilmiş Eğitim Planı (BEP) Matematik Gelişim Ölçeği ve Formu",
    description: "Özel eğitim gereksinimi olan öğrenciler için kazanım basitleştirme, uzun ve kısa dönemli amaç belirleme BEP formu.",
    categoryId: "cat_rehberlik",
    subCategoryIds: ["cat_temel"],
    schoolType: "Tüm Okullar",
    gradeLevel: "İlkokul",
    classNumber: "3. Sınıf",
    lesson: "Matematik",
    branch: "Özel Eğitim & Rehberlik",
    subject: "BEP Gelişim Raporu",
    term: "1. Dönem",
    docType: "BEP Planı",
    year: "2025-2026",
    fileUrl: "/assets/docs/3_sinif_matematik_bep_formu.pdf",
    fileName: "3_sinif_matematik_bep_formu.pdf",
    fileType: "pdf",
    fileSizeBytes: 180000,
    tags: ["bep planı", "özel eğitim", "rehberlik", "matematik"],
    source: "AI Üretimi",
    authorId: "usr_1",
    authorName: "2Evrak AI Ajanı",
    status: "revision_required",
    isSoftDeleted: false,
    downloadCount: 820,
    viewCount: 2900,
    rating: 4.7,
    seo: {
      metaTitle: "3. Sınıf Matematik BEP Planı Şablonu | 2Evrak",
      metaDescription: "İlkokul 3. sınıf kaynaştırma öğrencileri için MEB uyumlu BEP planı ve değerlendirme formu.",
      keywords: ["bep planı", "kaynaştırma", "özel eğitim evrakı"],
    },
    createdAt: "2026-09-08 11:10",
    updatedAt: "2026-09-10 16:45",
  },
  {
    id: "doc_6",
    title: "Eski Müfredat 8. Sınıf Fen Deneme Sınavı (Arşivlenmiş)",
    description: "Geçen yıla ait arşiv fen bilimleri deneme sınavı.",
    categoryId: "cat_ortaokul_8",
    subCategoryIds: [],
    schoolType: "Devlet Ortaokulu",
    gradeLevel: "Ortaokul",
    classNumber: "8. Sınıf",
    lesson: "Fen Bilimleri",
    branch: "Fen Bilimleri",
    subject: "DNA ve Genetik Kod",
    term: "1. Dönem",
    docType: "Yazılı Sınavı",
    year: "2024-2025",
    fileUrl: "/assets/docs/eski_fen_deneme.pdf",
    fileName: "eski_fen_deneme.pdf",
    fileType: "pdf",
    fileSizeBytes: 520000,
    tags: ["arşiv", "fen", "deneme"],
    source: "Öğretmen Yüklemesi",
    authorId: "usr_5",
    authorName: "Hasan Çelik",
    status: "archived",
    isSoftDeleted: true,
    deletedAt: "2026-09-01 12:00",
    deletedBy: "usr_1",
    downloadCount: 910,
    viewCount: 3100,
    rating: 4.2,
    seo: {
      metaTitle: "Arşiv: 8. Sınıf Fen Denemesi | 2Evrak",
      metaDescription: "Arşiv evrak.",
      keywords: ["arşiv"],
    },
    createdAt: "2024-11-10 10:00",
    updatedAt: "2026-09-01 12:00",
  },
];

export const initialContents: ContentItem[] = [
  {
    id: "cnt_1",
    title: "MEB 2025-2026 Türkiye Yüzyılı Maarif Modeli Öğretmen Kılavuzu Yayımlandı",
    slug: "meb-2025-maarif-modeli-ogretmen-kilavuzu",
    type: "news",
    summary: "Bakanlık tarafından hazırlanan yeni eğitim modelinde ders planlarının kazanım yapısı ve ölçme süreçleri açıklandı.",
    body: "Millî Eğitim Bakanlığı, tüm kademelerde uygulanacak yeni müfredat programına ilişkin kapsamlı uygulama yönergesini paylaştı. Bu rehber ile öğretmenlerimizin zümre kararlarını alırken dikkat etmesi gereken 8 temel unsur sıralandı. Detaylı şablonlar 2Evrak üzerinden indirilebilir.",
    coverImageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80",
    tags: ["meb haber", "maarif modeli", "müfredat", "öğretmen rehberi"],
    status: "published",
    authorName: "Zeynep Kaya",
    publishedAt: "2026-09-10 11:30",
    views: 18450,
    seo: {
      metaTitle: "MEB 2025 Maarif Modeli Öğretmen Kılavuzu | 2Evrak Haber",
      metaDescription: "Yeni MEB müfredatı ile zümre ve yıllık planlarda değişen kurallar ve öğretmen kılavuzu.",
    },
    aiGeneratedFields: {
      summaryGenerated: true,
      seoGenerated: true,
      socialCopyGenerated: true,
    },
  },
  {
    id: "cnt_2",
    title: "Açık Uçlu Sınav Sorusu Hazırlarken Dikkat Edilecek 5 Pedagojik Kural",
    slug: "acik-uclu-sinav-sorusu-hazirlama-rehberi",
    type: "guide",
    summary: "Ölçme ve Değerlendirme yönetmeliğine göre ortak sınavlarda öğrenci analizini kolaylaştıran soru hazırlama teknikleri.",
    body: "Ortak sınavlarda çoktan seçmeli sorulardan açık uçlu sorulara geçiş sürecinde en önemli husus puanlama anahtarının (rubrik) objektifliğidir. Soru kökünün netliği, öğrencinin bilişsel basamağı ve aşamalı puan baremleri bu rehberde incelenmiştir.",
    coverImageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80",
    tags: ["ölçme değerlendirme", "açık uçlu sorular", "rubrik", "öğretmen rehberi"],
    status: "published",
    authorName: "Mustafa Demir",
    publishedAt: "2026-09-08 14:15",
    views: 12300,
    seo: {
      metaTitle: "Açık Uçlu Sınav Sorusu Hazırlama Rehberi | 2Evrak",
      metaDescription: "MEB ortak sınavlar için açık uçlu sınav soruları ve rubrik hazırlama yöntemleri.",
    },
    aiGeneratedFields: {
      summaryGenerated: true,
      seoGenerated: true,
      socialCopyGenerated: false,
    },
  },
  {
    id: "cnt_3",
    title: "Zümre Başkanları İçin Dijital Arşivleme ve Takvim Planlaması",
    slug: "zumre-baskanlari-dijital-arsivleme",
    type: "article",
    summary: "Okul içi zümre koordinasyonunda evrak kaybını önleyen ve MEBBİS onaylarını hızlandıran modern yöntemler.",
    body: "Zümre başkanlarının her dönem başında ve sonunda hazırladığı onlarca sayfalık toplantı tutanakları artık 2Evrak dijital zümre modülü ile otomatik birleştirilip PDF formatında çıktı alınabilmektedir...",
    coverImageUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&auto=format&fit=crop&q=80",
    tags: ["zümre başkanı", "dijital arşiv", "mebbis"],
    status: "in_review",
    authorName: "Prof. Dr. Ahmet Yılmaz",
    views: 450,
    seo: {
      metaTitle: "Zümre Başkanları Dijital Arşiv Rehberi | 2Evrak",
      metaDescription: "Zümre evraklarını tek tıkla dijital arşivleme rehberi.",
    },
  },
];

export const initialSocialAccounts: SocialAccount[] = [
  { id: "soc_x", platform: "twitter", accountName: "2Evrak Resmi X", handle: "@2EvrakCom", isConnected: true, followersCount: 142000 },
  { id: "soc_tg", platform: "telegram", accountName: "2Evrak Öğretmenler Kanalı", handle: "@2evrak_duyuru", isConnected: true, followersCount: 98500 },
  { id: "soc_ig", platform: "instagram", accountName: "2Evrak Instagram", handle: "@2evrak.official", isConnected: true, followersCount: 65400 },
  { id: "soc_li", platform: "linkedin", accountName: "2Evrak Eğitim Teknolojileri", handle: "company/2evrak", isConnected: true, followersCount: 28900 },
  { id: "soc_fb", platform: "facebook", accountName: "2Evrak Öğretmen Topluluğu", handle: "groups/2evrak", isConnected: true, followersCount: 81200 },
  { id: "soc_yt", platform: "youtube", accountName: "2Evrak Akademi", handle: "@2evrak_akademi", isConnected: false, followersCount: 14000 },
];

export const initialSocialPosts: SocialPost[] = [
  {
    id: "sp_1",
    referenceType: "document",
    referenceId: "doc_1",
    targetPlatforms: ["twitter", "telegram", "linkedin"],
    contentPerPlatform: {
      twitter: "📚 2025-2026 Sene Başı Matematik Zümre Tutanağı ve Yıllık Plan şablonları yayında! MEB güncel müfredatına tam uyumlu ücretsiz indirin 👇\n#Öğretmen #MEB #MatematikZümresi #2Evrak",
      telegram: "📢 YENİ EVRAK: 2025-2026 Sene Başı Matematik Zümre Tutanağı paylaşıldı. Word (.docx) olarak indirmek için bağlantıya tıklayabilirsiniz: https://2evrak.com/d/doc_1",
      linkedin: "Değerli matematik öğretmenlerimiz; yeni eğitim dönemi için hazırladığımız kapsamlı Sene Başı Zümre Tutanağı ve Maarif Modeli çerçeve planı platformumuzda erişime açılmıştır.",
      facebook: "",
      instagram: "",
      youtube: "",
    },
    status: "published",
    publishedAt: "2026-09-11 10:30",
    metrics: {
      impressions: 34200,
      engagements: 1890,
      shares: 420,
    },
  },
  {
    id: "sp_2",
    referenceType: "content",
    referenceId: "cnt_1",
    targetPlatforms: ["twitter", "telegram"],
    contentPerPlatform: {
      twitter: "🚨 MEB'den önemli duyuru: Türkiye Yüzyılı Maarif Modeli uygulama kılavuzu açıklandı. Öğretmenlerimizin bilmesi gereken 8 kritik maddeyi derledik 🧵👇 #MEB #Öğretmen",
      telegram: "🚨 MEB Maarif Modeli Kılavuzu: Zümre ve yıllık planlarda nelerin değiştiğini içeren detaylı analiz yazımız yayında!",
      linkedin: "",
      facebook: "",
      instagram: "",
      youtube: "",
    },
    status: "scheduled",
    scheduledFor: "2026-09-13 09:00",
  },
];

export const initialDashboardWidgets: DashboardWidget[] = [
  { id: "w_kpi_overview", title: "Genel Sistem KPI Özeti", category: "kpi", size: "full", order: 1, isVisible: true, componentKey: "KpiSummaryWidget" },
  { id: "w_realtime_downloads", title: "Canlı İndirme & Ziyaretçi Hacmi", category: "chart", size: "medium", order: 2, isVisible: true, componentKey: "DownloadsChartWidget" },
  { id: "w_moderation_queue", title: "Merkezi Moderasyon Kuyruğu", category: "queue", size: "medium", order: 3, isVisible: true, componentKey: "ModerationQueueWidget" },
  { id: "w_workers_status", title: "Worker & Arka Plan Görev Motoru", category: "queue", size: "small", order: 4, isVisible: true, componentKey: "WorkersStatusWidget" },
  { id: "w_ad_revenue", title: "Reklam Gösterim & Gelir Takibi", category: "chart", size: "small", order: 5, isVisible: true, componentKey: "AdRevenueWidget" },
  { id: "w_ai_agents_usage", title: "AI Ajanları Token Tüketimi", category: "chart", size: "small", order: 6, isVisible: true, componentKey: "AiAgentsUsageWidget" },
  { id: "w_quick_actions", title: "Hızlı Yönetim Aksiyonları", category: "quick_action", size: "medium", order: 7, isVisible: true, componentKey: "QuickActionsWidget" },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "notif_1",
    type: "moderation",
    title: "Onay Bekleyen Evrak",
    message: "Mustafa Demir tarafından '7. Sınıf Fen Bilimleri 1. Yazılı' evrakı incelemeye sunuldu.",
    channels: ["site", "push"],
    targetGroup: "admins",
    isRead: false,
    createdAt: "2026-09-12 09:55",
    actionUrl: "/moderation",
  },
  {
    id: "notif_2",
    type: "scraper",
    title: "MEB Duyuru Scraper Tamamlandı",
    message: "MEB Resmi Duyurular kaynağından 2 yeni kılavuz ve 1 yönetmelik başarıyla çekildi.",
    channels: ["site"],
    targetGroup: "admins",
    isRead: false,
    createdAt: "2026-09-12 08:06",
    actionUrl: "/scraper",
  },
  {
    id: "notif_3",
    type: "security",
    title: "Şüpheli Rate Limit Aktivitesi",
    message: "194.26.29.112 IP adresinden dakikada 480 indirme isteği engellendi.",
    channels: ["site", "email"],
    targetGroup: "admins",
    isRead: true,
    createdAt: "2026-09-11 22:40",
    actionUrl: "/security",
  },
  {
    id: "notif_4",
    type: "system",
    title: "1 Milyon Öğretmen Altyapı Güncellemesi",
    message: "Redis önbellek kümesi ve worker havuzu başarıyla v2.4 sürümüne yükseltildi.",
    channels: ["site"],
    targetGroup: "all_teachers",
    isRead: true,
    createdAt: "2026-09-10 14:00",
  },
];

export const initialPages: CustomPage[] = [
  {
    id: "page_hakkimizda",
    title: "Hakkımızda ve Misyonumuz",
    slug: "hakkimizda",
    status: "published",
    order: 1,
    seoTitle: "Hakkımızda | 2Evrak Öğretmen Platformu",
    seoDescription: "2Evrak, Türkiye genelindeki 1 milyon öğretmenin bürokratik evrak yükünü hafifletmek için kurulmuş açık platformdur.",
    schemaType: "AboutPage",
    publishedAt: "2025-01-01",
    blocks: [
      {
        id: "b_1",
        type: "hero",
        title: "1 Milyon Öğretmenin Dijital Çözüm Ortağı",
        content: "Eğitimde vakit, kağıt işlerine değil öğrencilere ayrılmalı. 2Evrak bu vizyonla hayata geçirildi.",
      },
      {
        id: "b_2",
        type: "two_column",
        title: "Neden 2Evrak?",
        content: "Gelişmiş AI ajanları, MEB müfredatı ile %100 senkronize yıllık planlar ve ortak sınav havuzuyla öğretmenlerimizin yanında yer alıyoruz.",
      },
      {
        id: "b_3",
        type: "faq",
        title: "Sıkça Sorulan Sorular",
        content: "Evraklar ücretsiz mi? Evet, Temel Öğretmen paketimizle tüm standart evraklar tamamen ücretsizdir.",
      },
    ],
  },
  {
    id: "page_iletisim",
    title: "İletişim & Zümre Destek Masası",
    slug: "iletisim",
    status: "published",
    order: 2,
    seoTitle: "İletişim | 2Evrak Destek",
    seoDescription: "Sorularınız, önerileriniz veya zümre işbirlikleriniz için 2Evrak ekibiyle iletişime geçin.",
    schemaType: "ContactPage",
    publishedAt: "2025-01-01",
    blocks: [
      {
        id: "b_c1",
        type: "contact_form",
        title: "Bize Ulaşın",
        content: "Mesajınız doğrudan branş koordinatörlerimize iletilmektedir.",
      },
    ],
  },
];

export const initialMenuItems: MenuItem[] = [
  { id: "m_1", parentId: null, label: "Ana Sayfa", type: "url", targetValue: "/", order: 1, openInNewTab: false, isActive: true },
  { id: "m_2", parentId: null, label: "Evrak Havuzu", type: "category", targetValue: "cat_temel", order: 2, openInNewTab: false, isActive: true },
  { id: "m_2_1", parentId: "m_2", label: "Zümre Tutanakları", type: "category", targetValue: "cat_zumre", order: 1, openInNewTab: false, isActive: true },
  { id: "m_2_2", parentId: "m_2", label: "MEB Ortak Yazılılar", type: "category", targetValue: "cat_yazili", order: 2, openInNewTab: false, isActive: true },
  { id: "m_2_3", parentId: "m_2", label: "2025-2026 Yıllık Planlar", type: "category", targetValue: "cat_planlar", order: 3, openInNewTab: false, isActive: true },
  { id: "m_3", parentId: null, label: "AI Öğretmen Ajanları", type: "url", targetValue: "/ai-hub", order: 3, requiredPackage: "pkg_pro", openInNewTab: false, isActive: true },
  { id: "m_4", parentId: null, label: "Rehberlik & BEP", type: "category", targetValue: "cat_rehberlik", order: 4, openInNewTab: false, isActive: true },
  { id: "m_5", parentId: null, label: "Haberler & Rehberler", type: "url", targetValue: "/haberler", order: 5, openInNewTab: false, isActive: true },
  { id: "m_6", parentId: null, label: "Hakkımızda", type: "page", targetValue: "page_hakkimizda", order: 6, openInNewTab: false, isActive: true },
];

export const initialMediaFiles: MediaFile[] = [
  {
    id: "med_1",
    name: "2evrak_ogretmen_banner_2025.png",
    url: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&auto=format&fit=crop&q=80",
    mimeType: "image/png",
    sizeBytes: 1240000,
    category: "image",
    uploadedBy: "Prof. Dr. Ahmet Yılmaz",
    createdAt: "2026-09-01 10:00",
    isScannedSafe: true,
    metadata: { dimensions: "1920x1080", checksumSha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    usages: [{ type: "page", id: "page_hakkimizda", name: "Hakkımızda Sayfası" }],
    isOrphan: false,
  },
  {
    id: "med_2",
    name: "meb_ortak_sinav_kilavuzu_2025.pdf",
    url: "/assets/docs/ortak_sinav_kilavuz.pdf",
    mimeType: "application/pdf",
    sizeBytes: 2450000,
    category: "document",
    uploadedBy: "Zeynep Kaya",
    createdAt: "2026-09-10 12:30",
    isScannedSafe: true,
    metadata: { checksumSha256: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08" },
    usages: [{ type: "document", id: "doc_2", name: "7. Sınıf Türkçe Sınavı" }],
    isOrphan: false,
  },
  {
    id: "med_3",
    name: "kullanilmayan_gecici_taslak.docx",
    url: "/assets/docs/temp_draft.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    sizeBytes: 450000,
    category: "document",
    uploadedBy: "Hasan Çelik",
    createdAt: "2026-08-20 09:15",
    isScannedSafe: true,
    metadata: { checksumSha256: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8" },
    usages: [],
    isOrphan: true, // Sahipsiz dosya
  },
];

export const initialFilterDefinitions: FilterDefinition[] = [
  {
    id: "f_okul_turu",
    key: "schoolType",
    label: "Okul Türü",
    options: ["Devlet Okulu", "Özel Okul", "BİLSEM", "İmam Hatip", "Fen Lisesi", "Mesleki ve Teknik (MTAL)", "Güzel Sanatlar & Spor"],
    order: 1,
    isMultiSelect: true,
    isSystemCore: true,
  },
  {
    id: "f_kademe",
    key: "gradeLevel",
    label: "Kademe",
    options: ["Okul Öncesi", "İlkokul", "Ortaokul", "Lise (Ortaöğretim)", "Özel Eğitim"],
    order: 2,
    isMultiSelect: true,
    isSystemCore: true,
  },
  {
    id: "f_sinif",
    key: "classNumber",
    label: "Sınıf",
    options: ["Ana Sınıfı", "1. Sınıf", "2. Sınıf", "3. Sınıf", "4. Sınıf", "5. Sınıf", "6. Sınıf", "7. Sınıf", "8. Sınıf (LGS)", "9. Sınıf", "10. Sınıf", "11. Sınıf", "12. Sınıf (YKS)"],
    order: 3,
    isMultiSelect: true,
    isSystemCore: true,
  },
  {
    id: "f_ders",
    key: "lesson",
    label: "Ders",
    options: ["Türkçe", "Matematik", "Fen Bilimleri", "Sosyal Bilgiler", "İngilizce", "Din Kültürü", "Fizik", "Kimya", "Biyoloji", "Tarih", "Coğrafya", "Felsefe", "Bilişim Teknolojileri", "Görsel Sanatlar", "Müzik", "Beden Eğitimi"],
    order: 4,
    isMultiSelect: true,
    isSystemCore: true,
  },
  {
    id: "f_donem",
    key: "term",
    label: "Dönem",
    options: ["Sene Başı", "1. Dönem 1. Yazılı", "1. Dönem 2. Yazılı", "1. Dönem Sonu", "2. Dönem Başı", "2. Dönem 1. Yazılı", "2. Dönem 2. Yazılı", "Yıl Sonu"],
    order: 5,
    isMultiSelect: false,
    isSystemCore: true,
  },
  {
    id: "f_evrak_turu",
    key: "docType",
    label: "Evrak Türü",
    options: ["Yıllık Plan", "Ders Planı (40 Dk)", "Zümre Tutanağı", "Ortak Yazılı Sınavı", "Çalışma Kağıdı", "Kulüp Dosyası", "ŞÖK Kararları", "Veli Toplantısı Tutanağı", "BEP Planı", "Rehberlik Evrakı", "Proje Ödevi Formu"],
    order: 6,
    isMultiSelect: true,
    isSystemCore: true,
  },
  {
    id: "f_yil",
    key: "year",
    label: "Eğitim Öğretim Yılı",
    options: ["2025-2026 (Güncel)", "2024-2025", "2023-2024", "2022-2023"],
    order: 7,
    isMultiSelect: false,
    isSystemCore: true,
  },
];

export const initialAIAgents: AIAgent[] = [
  {
    key: "icerik_ajani",
    name: "İçerik Ajanı",
    badge: "EDİTÖRYAL",
    description: "Öğretmenler için pedagojik makale, rehber ve haber taslakları oluşturur.",
    iconName: "FileText",
    defaultPrompt: "7. Sınıf Fen Bilimleri öğretmenleri için 'Güneş Sistemi konusunu eğlenceli işleme rehberi' başlığıyla 400 kelimelik zengin bir blog yazısı hazırla.",
    exampleInputs: [
      "Yeni MEB Maarif Modeline göre ders işleme stratejileri rehberi",
      "Sınıf içi odaklanmayı artıran 5 dakikalık dikkat etkinlikleri bülteni",
    ],
    provider: "gemini-3.8-flash",
    runsCount: 14200,
    avgResponseSec: 1.4,
  },
  {
    key: "dokuman_ajani",
    name: "Doküman Ajanı",
    badge: "BÜROKRASİ & MEVZUAT",
    description: "MEB mevzuatına %100 uyumlu zümre tutanağı, yıllık plan ve kurul kararları üretir.",
    iconName: "FolderOpen",
    defaultPrompt: "9. Sınıf Bilişim Teknolojileri dersi için 2025-2026 sene başı zümre toplantı tutanağı şablonu oluştur. Gündem maddeleri ve kararları içersin.",
    exampleInputs: [
      "İlkokul 4. sınıf matematik sene başı zümre tutanağı",
      "Ortaokul Türkçe zümresi başarıyı artırıcı tedbirler raporu",
    ],
    provider: "gemini-3.8-flash",
    runsCount: 38900,
    avgResponseSec: 1.8,
  },
  {
    key: "yazili_soru_ajani",
    name: "Yazılı Soru Ajanı",
    badge: "ÖLÇME & DEĞERLENDİRME",
    description: "MEB senaryo ve konu dağılım tablolarına göre açık uçlu sınav soruları ve rubrik cevap anahtarları üretir.",
    iconName: "CheckCircle2",
    defaultPrompt: "6. Sınıf Matematik 'Kesirlerle Toplama ve Çıkarma' kazanımı için Senaryo 1 formatında 5 adet açık uçlu soru ve her birinin puanlı rubrik çözümünü yaz.",
    exampleInputs: [
      "8. Sınıf LGS Türkçe Fiilimsiler için 4 adet yeni nesil beceri temelli soru",
      "10. Sınıf Tarih 1. Dönem 1. Yazılı için açık uçlu soru seti ve cevap anahtarı",
    ],
    provider: "gemini-3.8-flash",
    runsCount: 52400,
    avgResponseSec: 2.1,
  },
  {
    key: "ders_plani_ajani",
    name: "Ders Planı Ajanı",
    badge: "5E MODELİ",
    description: "40 dakikalık MEB ders planı (Giriş, Keşfetme, Açıklama, Derinleştirme, Değerlendirme) hazırlar.",
    iconName: "Clock",
    defaultPrompt: "5. Sınıf Fen Bilimleri 'Sürtünme Kuvveti' konusu için 40 dakikalık 5E modeli ders planı ve çıkış bileti (exit ticket) soruları hazırla.",
    exampleInputs: [
      "7. Sınıf İngilizce 'Biographies' ünitesi için 40 dakikalık konuşma odaklı plan",
      "4. Sınıf Sosyal Bilgiler 'Milli Mücadele Kahramanları' ders planı",
    ],
    provider: "gemini-3.8-flash",
    runsCount: 29100,
    avgResponseSec: 1.6,
  },
  {
    key: "evrak_ajani",
    name: "Evrak Ajanı",
    badge: "ŞÖK & KULÜP",
    description: "Şube Öğretmenler Kurulu (ŞÖK), veli toplantısı tutanağı ve sosyal kulüp evraklarını oluşturur.",
    iconName: "ClipboardList",
    defaultPrompt: "8/A Sınıfı için 1. Dönem Sene Başı Şube Öğretmenler Kurulu (ŞÖK) toplantı raporu hazırla. LGS hazırlığı ve rehberlik kararlarını vurgula.",
    exampleInputs: [
      "Gezi, Tanıtma ve Turizm Kulübü yıllık çalışma planı ve tüzüğü",
      "1. Dönem Sene Başı Genel Veli Toplantısı Tutanak ve İmza Çizelgesi",
    ],
    provider: "gemini-3.8-flash",
    runsCount: 21300,
    avgResponseSec: 1.5,
  },
  {
    key: "seo_ajani",
    name: "SEO Ajanı",
    badge: "ARAMA OPTİMİZASYONU",
    description: "Doküman ve içerikler için Google ve arama motorları dostu meta veriler, schema JSON-LD ve kalite skoru analiz eder.",
    iconName: "Search",
    defaultPrompt: "'8. Sınıf Matematik LGS Deneme Sınavı Soruları' dokümanı için meta title, meta description, 5 anahtar kelime ve spam risk skorunu çıkar.",
    exampleInputs: [
      "Yıllık plan kategorisi için SEO optimizasyon önerileri",
      "Yeni eklenen blog makalesi için Google Rich Snippet şeması",
    ],
    provider: "gemini-3.8-flash",
    runsCount: 16800,
    avgResponseSec: 1.2,
  },
  {
    key: "moderasyon_ajani",
    name: "Moderasyon Ajanı",
    badge: "PEDAGOJİK GÜVENLİK",
    description: "Yüklenen içeriklerde telif, küfür, yanıltıcı bilgi ve pedagojik sakınca denetimi yapar.",
    iconName: "ShieldCheck",
    defaultPrompt: "Aşağıdaki metni pedagojik uygunluk, telif hakkı ve MEB müfredatına aykırılık yönünden denetle:\n'Öğrencilere ceza olarak teneffüse çıkmama yaptırımı uygulanacaktır.'",
    exampleInputs: [
      "Kullanıcı yorumlarında argo ve pedagojik olmayan ifadeleri filtreleme",
      "Yüklenen yazılı sınavında ticari yayın evi telif ihlali taraması",
    ],
    provider: "gemini-3.8-flash",
    runsCount: 64200,
    avgResponseSec: 0.9,
  },
  {
    key: "scraper_ajani",
    name: "Scraper Ajanı",
    badge: "VERİ SINIFLANDIRMA",
    description: "Web'den kazınan ham duyuru ve dökümanları analiz edip ders, sınıf ve evrak türüne otomatik eşleştirir.",
    iconName: "Cpu",
    defaultPrompt: "MEB sitesinden kazınan '2025 Yılı 1. Dönem ŞÖK Esasları Duyurusu' metnini ayrıştırıp sınıf, kademe ve evrak türünü JSON olarak sınıflandır.",
    exampleInputs: [
      "EBA'dan çekilen çalışma kağıtlarını kazanım koduna göre etiketleme",
      "ÖSYM duyuru metninden sınav tarihi ve başvuru süresini çıkarma",
    ],
    provider: "gemini-3.8-flash",
    runsCount: 19400,
    avgResponseSec: 1.1,
  },
  {
    key: "sosyal_ajani",
    name: "Sosyal Medya Ajanı",
    badge: "ÇOK KANALLI DAĞITIM",
    description: "Doküman ve duyuruları X, LinkedIn, Instagram ve Telegram formatlarına özelleştirerek paylaşım metni üretir.",
    iconName: "Share2",
    defaultPrompt: "'7. Sınıf Türkçe 1. Dönem 1. Yazılı Sınavı' dokümanı için X (Twitter) ve Telegram kanallarımıza uygun ilgi çekici 2 farklı paylaşım metni yaz.",
    exampleInputs: [
      "Yeni Maarif Modeli kılavuzu için LinkedIn uzman yazısı oluştur",
      "Instagram görseli altına öğretmenlere yönelik soru soran caption hazırla",
    ],
    provider: "gemini-3.8-flash",
    runsCount: 11200,
    avgResponseSec: 1.3,
  },
];

export const initialModerationItems: ModerationItem[] = [
  {
    id: "mod_1",
    targetType: "document",
    targetId: "doc_4",
    title: "Satranç Kulübü Yıllık Çalışma Dosyası",
    submittedBy: "Elif Şahin (Öğretmen)",
    submittedAt: "2026-09-11 14:20",
    status: "pending",
    aiSafetyScore: 98,
    aiSafetySummary: "Telif ihlali yok, pedagojik ilkelere uygun, MEB sosyal etkinlik yönetmeliği ile uyumlu.",
  },
  {
    id: "mod_2",
    targetType: "document",
    targetId: "doc_5",
    title: "Bireyselleştirilmiş Eğitim Planı (BEP) Matematik Gelişim Ölçeği",
    submittedBy: "2Evrak AI Ajanı",
    submittedAt: "2026-09-08 11:10",
    status: "revision_required",
    aiSafetyScore: 78,
    aiSafetySummary: "Özel eğitim standartlarında 2. kademe kazanım basamağı eksik, revizyon önerildi.",
    reviewerNotes: "BEP formundaki 3. hedef öğrenci düzeyine göre basitleştirilmeli.",
    reviewedBy: "Mustafa Demir",
    reviewedAt: "2026-09-10 16:45",
  },
  {
    id: "mod_3",
    targetType: "scraper_output",
    targetId: "job_1",
    title: "MEB 1. Dönem Ortak Sınav Kılavuzu (Scraper)",
    submittedBy: "Scraper Motoru (MEB Duyurular)",
    submittedAt: "2026-09-12 08:05",
    status: "in_review",
    aiSafetyScore: 100,
    aiSafetySummary: "Resmi MEB duyurusu doğrulandı. Dosya PDF bütünlüğü tam, duplicate bulunmadı.",
  },
  {
    id: "mod_4",
    targetType: "comment",
    targetId: "com_99",
    title: "Öğretmen Evrak Yorumu: 'Teşekkürler, çok faydalı oldu'",
    submittedBy: "Ahmet K. (Öğretmen)",
    submittedAt: "2026-09-12 09:30",
    status: "approved",
    aiSafetyScore: 100,
    aiSafetySummary: "Temiz ve olumlu geri bildirim.",
    reviewedBy: "Zeynep Kaya",
    reviewedAt: "2026-09-12 09:35",
  },
];

export const initialSEOSettings: SEOSettings = {
  robotsTxt: "User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /api/\nDisallow: /private/\n\nSitemap: https://2evrak.com/sitemap.xml",
  sitemapXmlGenerated: `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>https://2evrak.com/</loc><priority>1.0</priority><changefreq>daily</changefreq></url>
  <url><loc>https://2evrak.com/zumre-ve-kurul-tutanaklari</loc><priority>0.9</priority><changefreq>daily</changefreq></url>
  <url><loc>https://2evrak.com/yazili-sinavlar-ortak-sinavlar</loc><priority>0.9</priority><changefreq>daily</changefreq></url>
  <url><loc>https://2evrak.com/yillik-planlar</loc><priority>0.9</priority><changefreq>weekly</changefreq></url>
</urlset>`,
  defaultSchemaOrg: `{
  "@context": "https://schema.org",
  "@type": "EducationalOrganization",
  "name": "2Evrak",
  "url": "https://2evrak.com",
  "logo": "https://2evrak.com/logo.png",
  "description": "1 Milyon Öğretmen Hedefli Kapsamlı Doküman ve İçerik Yönetim Platformu"
}`,
  redirects: [
    { source: "/eski-planlar-2024", target: "/yillik-planlar", code: 301 },
    { source: "/meb-sinavlari-arsiv", target: "/yazili-sinavlar-ortak-sinavlar", code: 301 },
  ],
  brokenLinks404: [
    { path: "/dosyalar/eski_bep_2023.pdf", hits: 142, lastDetected: "2026-09-12 08:30" },
    { path: "/yazili-arsiv-link", hits: 38, lastDetected: "2026-09-11 19:15" },
  ],
  spamChecker: {
    totalDocumentsScanned: 4890,
    cleanRate: 99.4,
    flaggedKeywords: ["bedava para", "casino", "ödev yaptırma sitesi", "kopya satışı"],
  },
};

export const initialAnalytics: AnalyticsSummary = {
  totalTeachers: 142850,
  activeToday: 28410,
  totalDocuments: 48620,
  totalDownloads: 1845000,
  topSearchTerms: [
    { term: "matematik 1. dönem 1. yazılı açık uçlu", count: 34120 },
    { term: "sene başı zümre tutanağı 2025-2026", count: 28940 },
    { term: "türkçe maarif modeli yıllık plan", count: 22400 },
    { term: "satranç kulübü yıllık dosya", count: 18700 },
    { term: "bep formu ilkokul", count: 14200 },
  ],
  emptySearches: [
    { term: "11. sınıf yapay zeka ders planı", count: 320 },
    { term: "halk oyunları kulübü bütçe formu", count: 180 },
  ],
  downloadsPerDay: [
    { date: "06 Eyl", count: 48900 },
    { date: "07 Eyl", count: 56200 },
    { date: "08 Eyl", count: 82400 },
    { date: "09 Eyl", count: 112000 },
    { date: "10 Eyl", count: 145000 },
    { date: "11 Eyl", count: 168000 },
    { date: "12 Eyl", count: 184000 },
  ],
  branchBreakdown: [
    { branch: "Matematik", docCount: 11200, downloadCount: 540000 },
    { branch: "Türk Dili ve Edebiyatı / Türkçe", docCount: 9800, downloadCount: 460000 },
    { branch: "Fen Bilimleri / Fizik / Kimya / Biyoloji", docCount: 8400, downloadCount: 380000 },
    { branch: "Sınıf Öğretmenliği", docCount: 7900, downloadCount: 310000 },
    { branch: "Bilişim ve Teknoloji", docCount: 4200, downloadCount: 155000 },
  ],
  adPerformance: {
    impressions: 284450,
    clicks: 9850,
    ctr: 3.46,
    revenue: 25950,
  },
  aiTokenConsumption: [
    { agent: "Yazılı Soru Ajanı", tokens: 1420000 },
    { agent: "Doküman Ajanı", tokens: 1180000 },
    { agent: "Moderasyon Ajanı", tokens: 840000 },
    { agent: "Ders Planı Ajanı", tokens: 720000 },
    { agent: "İçerik Ajanı", tokens: 590000 },
  ],
  scraperSuccessRate: 98.6,
};

export const initialAuditLogs: AuditLogEntry[] = [
  {
    id: "log_1",
    actorId: "usr_1",
    actorName: "Prof. Dr. Ahmet Yılmaz",
    actorRole: "Süper Yönetici",
    action: "SETTINGS_UPDATE",
    targetType: "settings",
    targetId: "security",
    targetName: "İki Aşamalı Doğrulama (2FA) Politikası",
    previousValue: "optional",
    newValue: "mandatory_for_staff",
    ipAddress: "88.255.10.15",
    result: "success",
    timestamp: "2026-09-12 09:30:14",
  },
  {
    id: "log_2",
    actorId: "usr_2",
    actorName: "Zeynep Kaya",
    actorRole: "Baş Editör",
    action: "DOCUMENT_APPROVE",
    targetType: "document",
    targetId: "doc_2",
    targetName: "7. Sınıf Türkçe Ortak Yazılı Sınavı",
    previousValue: "in_review",
    newValue: "published",
    ipAddress: "176.240.12.8",
    result: "success",
    timestamp: "2026-09-12 08:45:00",
  },
  {
    id: "log_3",
    actorId: "usr_1",
    actorName: "Prof. Dr. Ahmet Yılmaz",
    actorRole: "Süper Yönetici",
    action: "USER_SUSPEND",
    targetType: "user",
    targetId: "usr_5",
    targetName: "Hasan Çelik",
    previousValue: "active",
    newValue: "suspended",
    ipAddress: "88.255.10.15",
    result: "success",
    timestamp: "2026-09-11 17:12:35",
  },
  {
    id: "log_4",
    actorId: "system_scraper",
    actorName: "Scraper Worker #1",
    actorRole: "Sistem Worker",
    action: "SCRAPE_EXECUTE",
    targetType: "scraper",
    targetId: "src_meb_duyurular",
    targetName: "MEB Resmi Duyurular",
    newValue: "14 kayıt başarıyla çekildi, 1 duplicate elendi",
    ipAddress: "10.0.4.12",
    result: "success",
    timestamp: "2026-09-12 08:05:22",
  },
];

export const initialSecurityMetrics: SecurityMetrics = {
  healthScore: 98,
  rbacEnforced: true,
  rateLimitBlockedRequests: 1420,
  ssrfAttemptsBlocked: 84,
  fileUploadThreatsBlocked: 12,
  activeSessions: 3420,
  recentThreatLogs: [
    {
      id: "thr_1",
      type: "SSRF_ATTEMPT",
      ip: "194.26.29.112",
      details: "Scraper test endpoint'ine 169.254.169.254 AWS metadata sorgusu gönderildi. Filtre tarafından engellendi.",
      timestamp: "2026-09-12 04:15",
      severity: "high",
    },
    {
      id: "thr_2",
      type: "RATE_LIMIT_BURST",
      ip: "45.154.255.89",
      details: "Doküman indirme API'sine 60 saniyede 620 istek yapıldı. IP geçici kara listeye alındı.",
      timestamp: "2026-09-11 23:40",
      severity: "medium",
    },
    {
      id: "thr_3",
      type: "MALICIOUS_MIME_UPLOAD",
      ip: "91.12.80.201",
      details: ".php uzantılı dosya pdf olarak yüklenmeye çalışıldı. MIME doğrulayıcı tarafından reddedildi.",
      timestamp: "2026-09-10 19:10",
      severity: "critical",
    },
  ],
};

export const initialAPIKeys: APIKeyItem[] = [
  {
    id: "key_1",
    name: "MEB Okul İdare Sistemi Entegrasyonu",
    keyPrefix: "2evrak_live_9a7b...",
    scopes: ["documents:read", "categories:read"],
    rateLimitPerMinute: 600,
    createdAt: "2025-01-15",
    lastUsedAt: "2026-09-12 09:58",
    isActive: true,
  },
  {
    id: "key_2",
    name: "EBA Mobil Uygulama Servis Anahtarı",
    keyPrefix: "2evrak_live_4f2c...",
    scopes: ["documents:read", "search:execute", "contents:read"],
    rateLimitPerMinute: 1200,
    createdAt: "2025-03-20",
    lastUsedAt: "2026-09-12 10:02",
    isActive: true,
  },
];

export const initialWebhooks: WebhookEndpoint[] = [
  {
    id: "wh_1",
    url: "https://ogretmenler.org/api/webhooks/new-doc",
    events: ["document.published", "announcement.created"],
    secret: "whsec_98afb762c9...",
    isActive: true,
    lastTriggeredAt: "2026-09-12 08:45",
    successRate: 99.8,
  },
];

export const initialQueueJobs: QueueJob[] = [
  {
    id: "job_q1",
    queue: "scraper_queue",
    title: "MEB Duyurular Otomatik Kazıma ve OCR Ayrıştırma",
    priority: "normal",
    status: "processing",
    attempts: 1,
    maxAttempts: 3,
    progressPercent: 65,
    startedAt: "2026-09-12 10:00:15",
    payload: { sourceId: "src_meb_duyurular", limit: 20 },
  },
  {
    id: "job_q2",
    queue: "ai_queue",
    title: "8. Sınıf Fen Bilimleri LGS 20 Soru ve Rubrik Üretimi",
    priority: "high",
    status: "processing",
    attempts: 1,
    maxAttempts: 2,
    progressPercent: 80,
    startedAt: "2026-09-12 10:01:00",
    payload: { agent: "yazili_soru_ajani", class: "8", lesson: "Fen" },
  },
  {
    id: "job_q3",
    queue: "pdf_ocr_queue",
    title: "2025-2026 Yıllık Plan DOCX -> PDF Önizleme Oluşturma",
    priority: "normal",
    status: "completed",
    attempts: 1,
    maxAttempts: 3,
    progressPercent: 100,
    startedAt: "2026-09-12 09:50:00",
    completedAt: "2026-09-12 09:50:08",
    payload: { docId: "doc_1" },
  },
  {
    id: "job_q4",
    queue: "social_queue",
    title: "Telegram ve X Kanalı Otomatik Paylaşım Dağıtımı",
    priority: "normal",
    status: "waiting",
    attempts: 0,
    maxAttempts: 3,
    progressPercent: 0,
    payload: { postId: "sp_2" },
  },
  {
    id: "job_q5",
    queue: "notification_queue",
    title: "28.000 Matematik Öğretmenine Yeni Zümre Bildirimi",
    priority: "high",
    status: "completed",
    attempts: 1,
    maxAttempts: 3,
    progressPercent: 100,
    startedAt: "2026-09-12 09:00:00",
    completedAt: "2026-09-12 09:01:40",
    payload: { branch: "Matematik", docId: "doc_1" },
  },
  {
    id: "job_q6",
    queue: "seo_queue",
    title: "Haftalık Kırık Link ve Spam Kalite Taraması",
    priority: "low",
    status: "waiting",
    attempts: 0,
    maxAttempts: 2,
    progressPercent: 0,
    payload: { fullScan: true },
  },
];

export const initialWorkerPoolStatus: WorkerPoolStatus = {
  totalWorkers: 12,
  activeWorkers: 8,
  jobsProcessedToday: 48920,
  avgDurationMs: 412,
  queues: {
    scraper_queue: { waiting: 2, processing: 1, completed: 840, failed: 4 },
    ai_queue: { waiting: 14, processing: 4, completed: 12400, failed: 12 },
    pdf_ocr_queue: { waiting: 5, processing: 2, completed: 9100, failed: 2 },
    social_queue: { waiting: 1, processing: 0, completed: 450, failed: 0 },
    notification_queue: { waiting: 3, processing: 1, completed: 25800, failed: 15 },
    seo_queue: { waiting: 1, processing: 0, completed: 330, failed: 1 },
  },
};
